src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ammount__c</fullName>
        <label>ammount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>endDate__c</fullName>
        <label>endDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>startDate__c</fullName>
        <label>startDate</label>
        <type>DateTime</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EnrollmentTransformer.cls
public with sharing class EnrollmentTransformer {


    public EnrollmentRequest toEnrollmentRequest(Lead lead){

        EnrollmentRequest enrollment = new EnrollmentRequest();
        enrollment.student.name = lead.Name;
        enrollment.student.document = lead.id;
        enrollment.student.phone = lead.phone;

        for (Course__c course : lead.Courses__r ) {

            EnrollmentRequest.Course courseRequest = new EnrollmentRequest.Course();
            courseRequest.code = Long.valueOf(course.name);
            courseRequest.startDate = course.startDate__c;
            courseRequest.endDate = course.endDate__c;
            courseRequest.ammount = course.ammount__c;
            enrollment.courses.add(courseRequest);
        
        }

        return enrollment;
        
    }
}