src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ammount__c</fullName>
        <label>ammount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>endDate__c</fullName>
        <label>endDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>startDate__c</fullName>
        <label>startDate</label>
        <type>DateTime</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeadRepository.cls
public virtual with sharing class LeadRepository {

    public Lead findById (String id) {
        return [ SELECT id, Name, Phone
                , ( SELECT id, Name, startDate__c, endDate__c, ammount__c from Courses__r) 
            FROM Lead
            WHERE id = :id ];
    }

    public virtual Lead findByDocumentNumber (String documentNumber) {

        return [ SELECT Id, Name, FirstName, LastName, Email, Phone, DocumentNumber__c
        , Street, State, PostalCode, City
            FROM Lead WHERE DocumentNumber__c =:documentNumber 
            Order by CreatedDate desc LIMIT 1];
    } 

    public virtual Lead save (Lead lead) {
        if (lead.id == null) {
            insert lead;
        } else {
            update lead;
        }
        return lead;
    }        
    
}