src/objects/EventConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Event Configuration</label>
</CustomObject>

src/objects/Queue__c.object
<CustomObject>
    <description>Responsavel por prover garantia de entrega para camada de integração</description>
    <fields>
        <fullName>EventName__c</fullName>
        <description>Event Name or Transaction Name</description>
        <label>Event Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionStackTrace__c</fullName>
        <description>Used only for error messages, fill this field using getStackTraceString() method</description>
        <label>Exception Stack Trace</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalCreationDate__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>External last modified date based on iDoc date (using the external system date/timezone) to ensure the integration between systems will keep the transactions sequence as they were triggered by the original System</description>
        <label>External Creation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>InternalId__c</fullName>
        <description>Internal ID from External system related to this event (used to identify original transaction from external system)</description>
        <externalId>true</externalId>
        <label>Internal ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsRetryDisabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identify if the retries should be executed for this event. If equal TRUE disable retries even if retry count is bigger than zero (can be used for errors as errors does not require retries)</description>
        <label>Is Retry Disable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ObjectId__c</fullName>
        <description>Object ID (internal Sales Force Id) related to this event (used to retrieve information to create the transaction to the receiver Account)</description>
        <externalId>true</externalId>
        <label>ObjectId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <description>Payload
(Valor do Objeto Corrente, para atribuir esta informação concatene o objeto a uma string e atribua este valor concatenado ao payload. Este Atributo podera ser utilizado no futuro para Determinar o estado do Evento Corrente dispensando o uso do RecordType QUEUED nos Objetos que necessitam gerenciamento de estado)</description>
        <label>Payload</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Receiver__c</fullName>
        <label>Receiver</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RetryCount__c</fullName>
        <defaultValue>10</defaultValue>
        <description>Identify the number of retries for this event</description>
        <label>Retry Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sender__c</fullName>
        <label>SenderAccount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusMessage__c</fullName>
        <description>Error Message from internal or external System</description>
        <label>Status Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DELIVERED</fullName>
                </value>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>QUEUED</fullName>
                </value>
                <value>
                    <fullName>SUCCESS</fullName>
                </value>
                <value>
                    <fullName>INVALID</fullName>
                </value>
                <value>
                    <fullName>DONE</fullName>
                </value>
                <value>
                    <fullName>PROCESSING</fullName>
                </value>
                <value>
                    <fullName>UNHANDLED</fullName>
                </value>
                <value>
                    <fullName>IGNORED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>businessDocumentCorrelatedNumber__c</fullName>
        <label>businessDocumentCorrelatedNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>businessDocument__c</fullName>
        <externalId>true</externalId>
        <label>businessDocumentNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>parentEvent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Correlated Event</description>
        <label>Parent Event</label>
        <referenceTo>Queue__c</referenceTo>
        <relationshipLabel>Correlateds</relationshipLabel>
        <relationshipName>correlateds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>QueueCode</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventQueueActiveRecord.cls
/**
 * @author: Eduardo Ribeiro de Carvalho - ercarval
 */
public abstract class EventQueueActiveRecord  {

    private Map<String, EventConfiguration__c> config;

    public static String[] PENDING_EVENTS = new String[] { EventQueueStatusType.SCHEDULED.name() };

    public EventQueueActiveRecord () {
        config = EventConfiguration__c.getAll();
    }

    public EventConfiguration__c getEventConfiguration (String eventName) {
        return config.get(eventName);
    }

    public Boolean hasHandlerFor (String eventName) {
        return config.containsKey(eventName);
    }

    public static void updateAll ( List<Queue__c> events ) {
        update events;
    }

    public static void createAll ( List<Queue__c> events ) {
        insert events;
    }

    public Queue__c save (Queue__c event) {

        if (event.id == null) {
            insert event;
            return event;
        }

        update event;
        return event;
    }

    public static void storePayloads(List<Attachment> attachments) {

        System.debug('\n\n\n Storing Payloads ' + attachments);

        try {

            upsert attachments;

        } catch (Exception e) {

            System.debug('\n\n\n [ EXCEPTION ] UNABLE TO STORE PAYLOAD ' + attachments);
            System.debug('\n\n\n ' + e);
            System.debug('\n\n\n --------------------------------------------- ');
            System.debug (e.getStackTraceString());

        }

    }



    public static List<Queue__c> findQueuedEvents (Set<String> keys) {
        return [Select q.status__c, q.statusMessage__c, q.sender__c, q.payload__c , q.retryCount__c, q.receiver__c, q.objectId__c, q.internalId__c, q.externalCreationDate__c, q.exceptionStackTrace__c, q.eventName__c, q.businessDocument__c, q.businessDocumentCorrelatedNumber__c, q.Name, q.Id From Queue__c q where q.id in :keys ] ;
    }

    virtual
    public Queue__c findOne (String id) {
        List<Queue__c> queues = findQueuedEvents ( new Set<String> {id});
        return (!queues.isEmpty()) ? queues.get(0) : null ;
    }

    public boolean hasQueuedEventsForBusinessDocument (String eventName, String businessDocumentNumber) {
        List<Queue__c> events =  [ Select id , name from Queue__c q
                                   where q.eventName__c  = :eventName
                                           and q.status__c = :EventQueueStatusType.QUEUED.name()
                                                   and q.businessDocument__c = :businessDocumentNumber
                                                           limit 1 ];
        return !events.isEmpty();
    }

    virtual
    public List<Queue__c> findLastEventsByNameAndBusinessDocumentNumber (String eventName, String businessDocumentNumber) {
        return [Select q.status__c, q.statusMessage__c, q.sender__c, q.retryCount__c, q.receiver__c, q.payload__c, q.objectId__c, q.internalId__c, q.externalCreationDate__c, q.exceptionStackTrace__c, q.eventName__c, q.businessDocument__c, q.businessDocumentCorrelatedNumber__c, q.Name, q.Id From Queue__c q
                where q.eventName__c  = :eventName
                                        and q.businessDocument__c = :businessDocumentNumber
                                                order by Queue__c.externalCreationDate__c desc
                                                limit 2] ;
    }

    public static List<Queue__c> findPendingQueuedEvents (DateTime lastCreationDate, Integer listSize) {
        return findPendingQueuedEvents ( PENDING_EVENTS, lastCreationDate, listSize );
    }

    public static List<Queue__c> findPendingQueuedEvents (String[] status,  DateTime lastCreationDate, Integer listSize) {
        return [ Select q.parentEvent__c, q.businessDocument__c, q.businessDocumentCorrelatedNumber__c, q.Status__c, q.StatusMessage__c, q.Sender__c, q.RetryCount__c, q.Receiver__c, q.Payload__c,  q.ObjectId__c, q.Name, q.LastModifiedDate,  q.IsRetryDisabled__c, q.InternalId__c, q.Id, q.ExternalCreationDate__c, q.ExceptionStackTrace__c, q.EventName__c, q.CreatedDate
                 From Queue__c q
                 where  q.status__c in :status
                 and q.createdDate < :lastCreationDate
                 order by q.createdDate asc
                 limit : listSize ];
    }

    public static List<Queue__c> findEventsWithError ( DateTime lastCreationDate, Integer listSize) {
        return [ Select q.parentEvent__c, q.businessDocument__c, q.businessDocumentCorrelatedNumber__c, q.Status__c, q.StatusMessage__c, q.Sender__c, q.RetryCount__c, q.Receiver__c, q.Payload__c,  q.ObjectId__c,  q.Name, q.LastModifiedDate,  q.IsRetryDisabled__c,  q.InternalId__c, q.Id, q.ExternalCreationDate__c, q.ExceptionStackTrace__c, q.EventName__c, q.CreatedDate
                 From Queue__c q
                 where  q.status__c = 'ERROR'
                                      and q.createdDate < :lastCreationDate
                                      and q.retryCount__c > 0
                                      and q.IsRetryDisabled__c = false
                                              order by q.createdDate asc
                                              limit : listSize ];
    }

    public static List<Queue__c> findPendingQueuedEvents (EventQueueStatusType status, Integer listSize) {
        return [ Select q.parentEvent__c, q.businessDocument__c, q.businessDocumentCorrelatedNumber__c, q.Status__c, q.StatusMessage__c, q.Sender__c, q.RetryCount__c, q.Receiver__c, q.Payload__c,  q.ObjectId__c,  q.Name, q.LastModifiedDate,  q.IsRetryDisabled__c,  q.InternalId__c, q.Id, q.ExternalCreationDate__c, q.ExceptionStackTrace__c, q.EventName__c, q.CreatedDate
                 From Queue__c q
                 where  q.status__c = :status.name()
                                      order by q.createdDate asc
                                      limit :listSize ];
    }

    virtual
    public List<Attachment> findAttachmentsForEvent (String eventId) {
        return [ SELECT Body, BodyLength, ContentType, CreatedById, CreatedDate, Description, Id, LastModifiedDate, Name, ParentId FROM Attachment where ParentId = :eventId order by  LastModifiedDate desc ];
    }

    virtual
    public List<Attachment> findLastPayloadProcessedForEvent (String eventId, String eventName) {
        return [ SELECT Body, BodyLength, ContentType, CreatedById, CreatedDate, Description, Id, LastModifiedDate, Name, ParentId FROM Attachment where ParentId = :eventId and name like :eventName + '%'  order by  LastModifiedDate desc limit 1 ];
    }

    public static List<Queue__c> findEventTypeForObject(String eventName, String objectId) {
        return [ SELECT Id from Queue__c where EventName__c = :eventName and ObjectId__c = :objectId];
    }

}