src/objects/Queue__c.object
<CustomObject>
    <description>Responsavel por prover garantia de entrega para camada de integração</description>
    <fields>
        <fullName>EventName__c</fullName>
        <description>Event Name or Transaction Name</description>
        <label>Event Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalId__c</fullName>
        <description>Internal ID from External system related to this event (used to identify original transaction from external system)</description>
        <externalId>true</externalId>
        <label>Internal ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsRetryDisabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identify if the retries should be executed for this event. If equal TRUE disable retries even if retry count is bigger than zero (can be used for errors as errors does not require retries)</description>
        <label>Is Retry Disable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ObjectId__c</fullName>
        <description>Object ID (internal Sales Force Id) related to this event (used to retrieve information to create the transaction to the receiver Account)</description>
        <externalId>true</externalId>
        <label>ObjectId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <description>Payload
(Valor do Objeto Corrente, para atribuir esta informação concatene o objeto a uma string e atribua este valor concatenado ao payload. Este Atributo podera ser utilizado no futuro para Determinar o estado do Evento Corrente dispensando o uso do RecordType QUEUED nos Objetos que necessitam gerenciamento de estado)</description>
        <label>Payload</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Receiver__c</fullName>
        <label>Receiver</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RetryCount__c</fullName>
        <defaultValue>10</defaultValue>
        <description>Identify the number of retries for this event</description>
        <label>Retry Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sender__c</fullName>
        <label>SenderAccount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusMessage__c</fullName>
        <description>Error Message from internal or external System</description>
        <label>Status Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DELIVERED</fullName>
                </value>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>QUEUED</fullName>
                </value>
                <value>
                    <fullName>SUCCESS</fullName>
                </value>
                <value>
                    <fullName>INVALID</fullName>
                </value>
                <value>
                    <fullName>DONE</fullName>
                </value>
                <value>
                    <fullName>PROCESSING</fullName>
                </value>
                <value>
                    <fullName>UNHANDLED</fullName>
                </value>
                <value>
                    <fullName>IGNORED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>businessDocumentCorrelatedNumber__c</fullName>
        <label>businessDocumentCorrelatedNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>businessDocument__c</fullName>
        <externalId>true</externalId>
        <label>businessDocumentNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>parentEvent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Correlated Event</description>
        <label>Parent Event</label>
        <referenceTo>Queue__c</referenceTo>
        <relationshipLabel>Correlateds</relationshipLabel>
        <relationshipName>correlateds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>QueueCode</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventBuilder.cls
/**
 * @author: Eduardo Ribeiro de Carvalho - ercarval
 */
public class EventBuilder {

    private Queue__c event;

    
    public EventBuilder createSynchronousOutboundEvent(String eventName) {
        return createOutboundEventFor(eventName)
               .disablingRetryStrategy()
               .withStatus(EventQueueStatusType.SUCCESS.name());
    }
    
    public EventBuilder createOutboundEventFor(String eventName) {
        return createEventFor(eventName)
               .usingRetryStrategy()
               .withSender('SALESFORCE');
    }

    public EventBuilder createEventFor(String eventName) {
        event = new Queue__c();
        return createEventBaseOn (event, eventName);
    }

    public EventBuilder createEventFor(EventType eventName) {
        return createEventFor (eventName.name());
    }

    public EventBuilder createEventBaseOn(Queue__c event, String eventName ) {
        this.event = event;
        this.event.eventName__c = eventName;
        this.event.status__c = EventQueueStatusType.QUEUED.name();
        return this;
    }

    public EventBuilder forEvent(String eventName) {
        event.eventName__c = eventName;
        return this;
    }

    public EventBuilder forObjectId (String id) {
        event.objectId__c = id;
        return this;
    }

    public EventBuilder usingRetryStrategy () {
        event.retryCount__c = 10;
        return this;
    }

    public EventBuilder disablingRetryStrategy () {
        event.retryCount__c = 0;
        event.IsRetryDisabled__c = true;
        return this;
    }

    public EventBuilder withRetryCount(Integer count) {
        event.retryCount__c = count;
        return this;
    }

    public EventBuilder withSender (String sender) {
        event.sender__c = sender;
        return this;
    }

    public EventBuilder correlatedTo (String eventId) {
        event.parentEvent__c = eventId;
        return this;
    }

    public EventBuilder withSameDocumentNumberForAllIdentifiers (String documentNumber ) {

        return this.forObjectId(documentNumber)
               .withBusinessDocumentNumber (documentNumber)
               .withBusinessDocumentCorrelatedNumber (documentNumber)
               .withInternalID(documentNumber);
    }

    public EventBuilder withReceiver (String receiver) {
        event.receiver__c = receiver;
        return this;
    }

    public EventBuilder withPayload (String payload) {
        event.payload__c = payload;
        return this;
    }

    public EventBuilder withStatus (String status) {
        event.status__c = status;
        return this;
    }

    public EventBuilder withStatusMessage (String message) {
        event.statusMessage__c = message;
        return this;
    }

    public EventBuilder withBusinessDocumentNumber (String businessDocumentNumber) {
        event.businessDocument__c = businessDocumentNumber;
        return this;
    }

    public EventBuilder withBusinessDocumentCorrelatedNumber (String businessDocumentCorrelatedNumber) {
        event.businessDocumentCorrelatedNumber__c  = businessDocumentCorrelatedNumber;
        return this;
    }

    public EventBuilder withInternalID (String internalId) {
        event.internalId__c  = internalId;
        return this;
    }

    public Queue__c build() {
        return event;
    }

    public EventQueue buildEvent() {
        return new EventQueue (event);
    }

    public EventQueue buildAndSave() {
        EventQueue event = new EventQueue (event);
        event.save();
        return event;
    }

    //only to improve dsl
    public EventQueue buildAndPusblish() {
        return buildAndSave();
    }

}