src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visitss</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VisitTH.cls
public with sharing class VisitTH extends TriggerHandler {

    List<Visit__c> newVisits;
    Map<Id, SObject> oldVisits;

    AccountVisitEnricher accountVisitEnricher;

    public VisitTH () {
        this( (List<Visit__c>) Trigger.new
        ,  (Map<Id, SObject>) Trigger.oldMap );
    }

    public VisitTH ( List<Visit__c> newVisits, Map<Id, SObject> oldVisits ) {
        this.newVisits = newVisits;
        this.oldVisits = oldVisits;

        accountVisitEnricher = new AccountVisitEnricher();
    }


    override
    public void afterInsert() {
        enrichAccountWithTotalOfVisits();
    }

    override
    public void afterUpdate() {
        enrichAccountWithTotalOfVisits();
    }

    public void enrichAccountWithTotalOfVisits () {
        Set<String> accountIds = FilterHelper.filterFieldIds('Account__c', newVisits );
        accountVisitEnricher.enrichWithTotalOfVisits( accountIds );
    }

}