src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visitss</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Checkin__c</fullName>
        <label>Check in</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Checkout__c</fullName>
        <label>Check out</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visitss</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rescheduled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rescheduled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ScheduleDate__c</fullName>
        <label>Schedule Date</label>
        <type>DateTime</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VisitRespository.cls
public class VisitRespository {

    public List<Visit__c> findAll () {
        return  [ SELECT Id, Name, ScheduleDate__c
        , Account__c, Account__r.Name
        , Lead__c, Lead__r.Name, Checkin__c, Checkout__c
        , Rescheduled__c 
        FROM Visit__c];
    }

    public List<Visit__c> findByAccount (String accountId) {
        return  [ SELECT Id, Name, ScheduleDate__c
        , Account__c, Account__r.Name
        , Lead__c, Lead__r.Name, Checkin__c, Checkout__c
        , Rescheduled__c 
        FROM Visit__c WHERE Account__c =: accountId];
    }


    public List<AggregateResult> findByAccountIds (Set<String> accountIds) {
        return  [ SELECT Account__c , COUNT (Id) total
            FROM Visit__c 
            WHERE Account__c in : accountIds  GROUP BY Account__c ];
    }

    public List<Visit__c> findByScheduleDate (Datetime scheduleDate) {
        return [ SELECT Id, Name, ScheduleDate__c
            , Account__c, Account__r.Name
            , Lead__c, Lead__r.Name, Checkin__c, Checkout__c
            , Rescheduled__c 
            FROM Visit__c WHERE  day_only(ScheduleDate__c) = :scheduleDate.date() ];
    }

}