src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visitss</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Checkin__c</fullName>
        <label>Check in</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Checkout__c</fullName>
        <label>Check out</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ScheduleDate__c</fullName>
        <label>Schedule Date</label>
        <type>DateTime</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VisitInboundService.cls
global with sharing class VisitInboundService {

    webservice
    static Visit create (Visit visit) {
        Visit__c visitToCreate = visit.toVisit(); 
        insert visitToCreate;

        visit.id = visitToCreate.Id;

        return visit;
    }

    global class Visit {

        webservice String id;
        webservice String accountId;
        webservice Datetime checkIn;
        webservice Datetime checkout;
        webservice Datetime scheduleDate;

        public Visit__c toVisit () {

            return new Visit__c (
                id = id
                , Account__c = accountId
                , Checkin__c = checkIn
                , Checkout__c = checkout
                , ScheduleDate__c = scheduleDate
            );

        }

    }


}